name: AutoTag

on:
  push:
    branches: [ master ]
  workflow_call:
    outputs:
      tag:
        value: ${{ jobs.create-tag.outputs.tag }}
  workflow_dispatch:

jobs:
  # Figure out the version string
  gitversion:
    uses: ./.github/workflows/gitversion.yml

  create-tag:
    uses: ./.github/workflows/tag.yml
    needs: [gitversion]
    with:
      name: ${{ needs.gitversion.outputs.fullSemVer }}